---
name: test
on:
  pull_request: {}
  issue_comment: {}
permissions: {}
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "$EVENT"
        env:
          EVENT: ${{toJson(github)}}
