---
name: test
on:
  push:
    branches: [dummy]
  pull_request:
    branches: [dummy]
permissions: {}
jobs:
  test:
    uses: suzuki-shunsuke/go-test-workflow/.github/workflows/test.yaml@v0.3.0-1
    with:
      aqua_version: v1.33.0
    permissions:
      pull-requests: write
      contents: read # To checkout private repository
