---
name: test
on:
  pull_request: {}
  issue_comment: {}
permissions: {}
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
      - run: echo "$EVENT"
        env:
          EVENT: ${{toJson(github)}}
