---
name: test
on:
  pull_request: {}
  issue_comment: {}
permissions: {}
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3
      - run: echo "$EVENT"
        env:
          EVENT: ${{toJson(github)}}
